### ISSUE TITLE
The time select popover is not quite accurate

### ISSUE THREAD

**Issue by BPaden** [gnumdk/lollypop#331]
Whether clicking and dragging the circle, or clicking somewhere on the progress bar, the time displayed in the popover is going to be several seconds off from where you actually end up jumping to.

**Comment by gnumdk** [comment]
Can't reproduce here

**Comment by gnumdk** [comment]
Theme?

**Comment by BPaden** [comment]
Adwaita, with the following tweaks:
```css
.header-bar {
	padding-top: 3px;
	padding-bottom: 3px;
	font-size: 9px;
}

.header-bar .button {
	padding-top: 5px;
	padding-bottom: 5px;
}
```

I think the best thing to do in this case is to check the value of the popover when jumping—that way the theme doesn't matter.
